# Generated by Django 3.2 on 2022-11-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='disability_type',
            field=models.CharField(choices=[('VISUALLY IMPAIRMENT', 'VISUALLY IMPAIRMENT'), ('PHYSICALLY CHALLENGE', 'PHYSICALLY CHALLENGE'), ('DEAF AND DAM', 'DEAF AND DAM'), ('DOWN SYNDROME', 'DOWN SYNDROME'), ('No disability', 'No disability')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='volunteer_type',
            field=models.CharField(choices=[('not a volunteer', 'not a volunteer'), ('GENRAL', 'GENERAL'), ('HEALTH', 'HEALTH'), ('BANKING', 'BANKING'), ('LEGAL RIGHT', 'LEGAL RIGHT'), ('MESSENGER', 'MESSENGER'), ('COUNCELLER', 'COUNCELLER'), ('TRANSPORT', 'TRANSPORT')], max_length=100),
        ),
    ]
