# Generated by Django 3.2.16 on 2022-11-27 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20221127_1342'),
        ('community', '0002_auto_20221127_1347'),
    ]

    operations = [
    ]
